Fix draft with bad connection
Infomaniak/android-kMail pull request #1046
Opened 2023-06-20 11:50 UTC by FabianDevel

A bug is remaining but we can't do anything about it : if the network is sufficent for a  send or save request to reach the server, but too weak to bring us the answer without a timeout, we don't have data to delete or update a draft. 
So it will be re-send or saved multiple times

2023-06-20 13:47 UTC, KevinBoulongne requested changes

2023-06-20 13:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +        // We keep these realm changes in a map to execute them all in a unique realm transaction at the end of the worker
```suggestion
        // Map containing the UUID of a Draft as key, and the callback function to update/delete it in Realm
        // We keep these Realm changes in a map to execute them all in a unique Realm transaction at the end of the worker
```

2023-06-20 13:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +        if (drafts.isEmpty()) return failWithErrors(errorMessageResIds)
```suggestion
        if (drafts.isEmpty()) return Result.failure()
```

2023-06-20 13:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +                    okHttpClient,
```suggestion
                    draft = draft,
                    mailboxUuid = mailbox.uuid,
                    okHttpClient = okHttpClient,
```

2023-06-20 13:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +        val dbActionOnDraft: ((MutableRealm, String) -> Unit)?,
Rename `dbActionOnDraft` into `realmActionOnDraft`.

2023-06-21 08:51 UTC, sirambd requested changes

2023-06-21 08:51 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +                draft.uploadAttachments(realm = mailboxContentRealm)
It's useless remove realm arg

2023-06-21 08:51 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +                        DraftController.getDraft(draftUuid)?.let(realm::findLatest)?.apply {
Try with the existing draft

2023-06-21 11:00 UTC, sirambd approved these changes

2023-06-21 13:34 UTC, merged