Remove unused variable in Thread
Infomaniak/android-kMail pull request #1100
Opened 2023-07-04 14:26 UTC by JorisBodin

2023-07-04 14:31 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
> -    var isScheduled: Boolean = false
iOs doesn't have it
And this feature will most likely require a DB migration anyway, as other information will be needed, such as date and time etc.
Might as well remove

2023-07-04 14:32 UTC, KevinBoulongne requested changes

2023-07-04 14:32 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
> +    @SerialName("answered")
This is useless, we create our own threads, we don't need to deserialise them _(except for the Search, but the only variable we use is the `messages` one)_.
All `@SerialName` in this file should be removed.

2023-07-04 14:34 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
> -    var isScheduled: Boolean = false
The concept of `scheduled` is present in a lot of places in the app. Removing it only here would create a discrepancy, and removing it everywhere will be a hassle when we'll want to put it back again in the future.

2023-07-05 06:50 UTC, KevinBoulongne approved these changes

2023-07-05 08:28 UTC, merged