Refactor folders items
Infomaniak/android-kMail pull request #1153
Opened 2023-07-20 07:23 UTC by FabianDevel

2023-07-25 10:40 UTC, LunarX requested changes

2023-07-25 10:40 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/SimpleFolderItemView.kt
I think we have an inconsistency in the naming pattern for the classes: `SimpleMailboxItemView`, `SimpleFolderItemView`, `FolderMenuDrawerItemView` and `MailboxMenuDrawerItemView`.

If we disregard the `ItemView` part, sometimes the "Mailbox" or "Folder" is at the start of the name and sometimes it's at the end. We should choose one of the two naming convention and use it for the four classes

2023-07-25 13:46 UTC, FabianDevel commented on app/src/main/res/values/styles.xml
> +    <style name="DecoratedTextItemShapeAppearance">
I'll add rounded to the name

2023-07-25 13:55 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
> +        }
A when will need a else clause because it's an assignment, so it would really just be a if-else at the end

2023-07-25 14:41 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/FolderItemView.kt
> +            indent = getDimensionPixelSize(R.styleable.DecoratedTextItemView_indent, indent)
This function has been removed

2023-07-25 14:46 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
> +        }
Done

2023-07-26 06:49 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
> +    }
I moved it to the indentable interface with the rest of the code needed for indentation

2023-07-26 07:49 UTC, LunarX approved these changes

2023-07-26 07:49 UTC, merged