Put back ThreadMode in UI
Infomaniak/android-kMail pull request #1194
Opened 2023-08-07 11:04 UTC by KevinBoulongne

2023-08-11 12:29 UTC, LunarX requested changes

2023-08-11 12:29 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingFragment.kt
> +                },
You prefer to keep it on multiple lines?

2023-08-11 12:29 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingViewModel.kt
> +        AccountUtils.reloadApp?.invoke()
Should the reload of the app be elsewhere than in a function that drops mailboxsContent? Like in the calling function right after the call to `dropAllMailboxesContent()`

2023-08-11 16:33 UTC, JorisBodin requested changes

2023-08-11 16:33 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingViewModel.kt
> +            RealmDatabase.deleteMailboxContent(mailbox.mailboxId, mailbox.userId)
java.lang.IllegalStateException: [RLM_ERR_DELETE_OPENED_REALM]: Cannot delete files of an open Realm: '/data/user/0/com.infomaniak.mail/files/Mailbox-xxx-xxx.realm' is still in use.

With multi user

2023-08-14 07:37 UTC, LunarX commented on app/src/main/res/values-it/strings.xml
You are missing the `settingsThreadModeWarningDescription` translation in italian

2023-08-16 07:49 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
> +            newThread.addFirstMessage(remoteMessage)
No, because we don't call `addFirstMessage()` each time we call `toThread()`.

2023-08-16 08:05 UTC, KevinBoulongne commented on app/src/main/res/drawable/ic_thread_mode_conversation.xml
> +  ~ Copyright (C) 2022-2023 Infomaniak Network SA
They've been renamed, so I guess yes? 🤷‍♂️

2023-08-16 08:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
> +            newThread.addFirstMessage(remoteMessage)
Finally, yes.

2023-08-16 13:13 UTC, LunarX approved these changes

2023-08-17 14:45 UTC, JorisBodin approved these changes

2023-08-17 14:45 UTC, merged