Update padding to design system
Infomaniak/android-kMail pull request #1204
Opened 2023-08-08 06:15 UTC by FabianDevel

2023-08-08 12:17 UTC, LunarX requested changes

2023-08-08 12:17 UTC, LunarX commented on app/src/main/res/layout/view_decorated_text_item.xml
> +            android:layout_marginEnd="@dimen/marginStandardMedium"
This margin is not indicated in the specs, we need to request it because this is the only missing one

2023-08-09 07:04 UTC, FabianDevel commented on app/src/main/res/layout/bottom_sheet_actions_menu.xml
> +            android:layout_marginBottom="@dimen/marginStandardSmall"
It is actually 8dp in the specs

2023-08-11 07:17 UTC, LunarX approved these changes

2023-08-11 07:17 UTC, merged