Split Body directly when fetching it, instead of when displaying the mail
Infomaniak/android-kMail pull request #1307
Opened 2023-08-30 11:55 UTC by KevinBoulongne

2023-08-31 12:13 UTC, LunarX approved these changes

2023-08-31 12:19 UTC, LunarX requested changes
There's no shimmering while the mails is being processed if you've already opened the email before

2023-09-05 09:28 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
> +                    newMessage.body?.splitBody == oldMessage.body?.splitBody &&
Do we use this equal operator without defining the equality method because in our case comparing objects by their instances is enough?

2023-09-05 09:49 UTC, sirambd approved these changes

2023-09-05 09:50 UTC, merged