Ai error messages
Infomaniak/android-kMail pull request #1393
Opened 2023-09-26 09:10 UTC by LunarX

Depends on #1392

2023-09-26 13:06 UTC, KevinBoulongne requested changes

2023-09-26 13:06 UTC, KevinBoulongne commented on app/src/main/res/values-fr/strings.xml
> +    <string name="aiErrorTooManyRequests">Il semblerait que vous avez effectué trop de requêtes en un court laps de temps. \n\nVeuillez patienter quelques instants.</string>
```suggestion
    <string name="aiErrorTooManyRequests">Il semblerait que vous avez effectué trop de requêtes en un court laps de temps.\n\nVeuillez patienter quelques instants.</string>
```
Change it on Loco too.

2023-09-26 13:06 UTC, KevinBoulongne commented on app/src/main/res/values-de/strings.xml
> +    <string name="aiErrorTooManyRequests">Es scheint, dass Sie in kurzer Zeit zu viele Suchanfragen gestellt haben. \n\nBitte haben Sie einen Moment Geduld.</string>
```suggestion
    <string name="aiErrorTooManyRequests">Es scheint, dass Sie in kurzer Zeit zu viele Suchanfragen gestellt haben.\n\nBitte haben Sie einen Moment Geduld.</string>
```
Change it on Loco too.

2023-09-26 13:06 UTC, KevinBoulongne commented on app/src/main/res/values-es/strings.xml
> +    <string name="aiErrorTooManyRequests">Parece que ha realizado demasiadas solicitudes en un corto espacio de tiempo. \n\nPor favor, espere unos momentos.</string>
```suggestion
    <string name="aiErrorTooManyRequests">Parece que ha realizado demasiadas solicitudes en un corto espacio de tiempo.\n\nPor favor, espere unos momentos.</string>
```
Change it on Loco too.

2023-09-26 13:06 UTC, KevinBoulongne commented on app/src/main/res/values-it/strings.xml
> +    <string name="aiErrorTooManyRequests">Sembra che abbiate fatto troppe richieste in un breve lasso di tempo. \n\nLa preghiamo di attendere qualche istante.</string>
```suggestion
    <string name="aiErrorTooManyRequests">Sembra che abbiate fatto troppe richieste in un breve lasso di tempo.\n\nLa preghiamo di attendere qualche istante.</string>
```
Change it on Loco too.

2023-09-26 13:06 UTC, KevinBoulongne commented on app/src/main/res/values/strings.xml
> +    <string name="aiErrorTooManyRequests">It seems you’ve made too many requests in a short amount of time. \n\nPlease wait a few moments.</string>
```suggestion
    <string name="aiErrorTooManyRequests">It seems you’ve made too many requests in a short amount of time.\n\nPlease wait a few moments.</string>
```
Change it on Loco too.

2023-09-26 13:06 UTC, KevinBoulongne commented on app/src/main/res/values/strings.xml
> +    <string name="aiErrorUnknown">An error has occurred. If this error persists, please contact our helpdesk. \n\nThank you for your patience.</string>
```suggestion
    <string name="aiErrorUnknown">An error has occurred. If this error persists, please contact our helpdesk.\n\nThank you for your patience.</string>
```
Change it on Loco too.

2023-09-26 13:08 UTC, KevinBoulongne requested changes

2023-09-26 13:08 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
> +                PropositionStatus.MAX_TOKEN_EXCEEDED,
```suggestion
                PropositionStatus.MAX_TOKENS_EXCEEDED,
```

2023-09-27 08:50 UTC, FabianDevel requested changes

2023-09-27 08:50 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
> +    }
```suggestion
    private fun setUiVisibilityState(state: UiState, errorType: PropositionStatus? = null) = when (state) {
        UiState.LOADING -> displayLoadingVisibility()
        UiState.PROPOSITION -> displayPropositionVisibility()
        UiState.ERROR -> displayErrorVisibility(errorType)
    }
```

2023-09-27 08:50 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
> +            }
Why this if? 

Wouldn't it work like this: 
```suggestion
        insertPropositionButton.isEnabled = displayRetryButton
        refineButton.isVisible = displayRetryButton
```

2023-09-27 12:08 UTC, KevinBoulongne approved these changes

2023-09-27 12:08 UTC, merged