Start fixing leak
Infomaniak/android-kMail pull request #1473
Opened 2023-10-12 14:34 UTC by FabianDevel

2023-10-12 15:52 UTC, KevinBoulongne requested changes

2023-10-12 15:52 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
> +
```suggestion
```

2023-10-13 09:44 UTC, sirambd approved these changes

2023-10-13 09:45 UTC, KevinBoulongne approved these changes

2023-10-13 09:47 UTC, merged