10. Split `fetchCredentials()` into more meaningful functions
Infomaniak/android-kMail pull request #1477
Opened 2023-10-13 09:02 UTC by KevinBoulongne

2023-10-13 09:25 UTC, FabianDevel requested changes

2023-10-13 09:25 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
> +            }
oneline this

2023-10-13 09:34 UTC, FabianDevel approved these changes

2023-10-13 10:33 UTC, sirambd approved these changes

2023-10-16 09:36 UTC, FabianDevel approved these changes

2023-10-16 09:37 UTC, merged