Update sync illustration and wording
Infomaniak/android-kMail pull request #1505
Opened 2023-10-19 13:06 UTC by LunarX

2023-10-19 15:13 UTC, KevinBoulongne requested changes

2023-10-19 15:35 UTC, KevinBoulongne commented on app/src/main/res/values/strings.xml
> +    <string name="syncCalendarsAndContactsDescriptionAndroid">Check your calendars in the Calendar and Contacts applications on your Android.</string>
Proposed french version : "Consultez vos contacts et calendriers directement depuis votre téléphone."

2023-10-20 07:33 UTC, KevinBoulongne commented on app/src/main/res/values/strings.xml
> +    <string name="syncCalendarsAndContactsDescriptionAndroid">Check your calendars in the Calendar and Contacts applications on your Android.</string>
"Consultez vos contacts et calendriers directement depuis votre appareil."

2023-10-20 09:30 UTC, JorisBodin approved these changes

2023-10-20 09:30 UTC, merged