Factorize `subBodies` fusion
Infomaniak/android-kMail pull request #1555
Opened 2023-11-15 14:56 UTC by LunarX

Also take subbodies into account when transforming previous message to plain text for the AI API call

Depends on #1554

2023-11-22 17:16 UTC, KevinBoulongne approved these changes

2023-11-23 12:56 UTC, FabianDevel requested changes

2023-11-23 12:56 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
> +            MessageBodyUtils.fuseSplitBodyAndSubBodies(previousBody, body.subBodies, message.uid)
```suggestion
            MessageBodyUtils.mergeSplitBodyAndSubBodies(previousBody, body.subBodies, message.uid)
```

2023-11-24 06:47 UTC, FabianDevel approved these changes

2023-11-24 12:12 UTC, merged