Save to kDrive
Infomaniak/android-kMail pull request #1570
Opened 2023-11-29 14:01 UTC by FabianDevel

Depends on #1569

2023-11-29 15:24 UTC, tevincent requested changes

2023-11-29 15:24 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt
> +}
```suggestion
object AttachmentIntentUtils {
    const val DOWNLOAD_ATTACHMENT_RESULT = "download_attachment_result"

    private const val DRIVE_PACKAGE = "com.infomaniak.drive"
    private const val DRIVE_CLASS = "com.infomaniak.drive.ui.SaveExternalFilesActivity"

    fun Attachment.openWithIntent(context: Context): Intent {
        val uri = FileProvider.getUriForFile(context, context.getString(R.string.ATTACHMENTS_AUTHORITY), getCacheFile(context))
        return Intent().apply {
            action = Intent.ACTION_VIEW
            flags = Intent.FLAG_GRANT_READ_URI_PERMISSION
            setDataAndType(uri, safeMimeType)
        }
    }

    fun Attachment.getIntentFromType(context: Context, intentType: AttachmentIntentType) = when (intentType) {
        OPEN_WITH -> openWithIntent(context)
        SAVE_TO_DRIVE -> saveToDriveIntent(context)
    }
    
    private fun Attachment.saveToDriveIntent(context: Context): Intent {
        val uri = FileProvider.getUriForFile(context, context.getString(R.string.ATTACHMENTS_AUTHORITY), getCacheFile(context))
        return Intent().apply {
            component = ComponentName(DRIVE_PACKAGE, DRIVE_CLASS)
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_STREAM, uri)
            setDataAndType(uri, safeMimeType)
        }
    }

    enum class AttachmentIntentType {
        OPEN_WITH, SAVE_TO_DRIVE
    }
}
```

Not mandatory. I just like to have public variable first, then private. Same for functions.

2023-11-30 07:31 UTC, tevincent approved these changes

2023-12-04 10:24 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt
> +            setDataAndType(uri, safeMimeType)
Why not using safeMimeType ? It offers a better support of mimeTypes without drawbacks

2023-12-08 07:42 UTC, LunarX approved these changes

2023-12-11 12:33 UTC, merged