Correctly place Snackbar depending on currently displayed fragments
Infomaniak/android-kMail pull request #1597
Opened 2023-12-11 08:13 UTC by KevinBoulongne

Depends on #1595

2023-12-11 14:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
> +                }
Done !

2023-12-11 14:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
> +                    threadListFragment?.binding?.newMessageFab
Done !

2023-12-11 16:41 UTC, FabianDevel requested changes

2023-12-11 16:41 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
> +            R.id.searchFragment -> (currentFragment as? SearchFragment)?.getAnchor()
as threadListFragment and searchFragment are both TwoPaneFragment, we could regroup this with an abstract getAnchor() in TwoPaneFragment so we only have 1 case

2023-12-18 13:29 UTC, LunarX approved these changes

2023-12-18 16:23 UTC, FabianDevel requested changes

2023-12-18 16:23 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
>              }
Oneline this if

2023-12-18 16:27 UTC, FabianDevel approved these changes

2023-12-21 09:34 UTC, merged