Fix wrong bars colors when opening BottomSheet
Infomaniak/android-kMail pull request #1650
Opened 2024-01-16 09:05 UTC by KevinBoulongne

2024-01-17 08:09 UTC, LunarX requested changes

2024-01-17 08:09 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
When building the branch, the first status bar is wrong, it's white instead of pink (secondary one)

2024-01-17 08:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Fixed.

2024-01-17 10:35 UTC, FabianDevel requested changes
This create bugs for some screen when recreating the activity (changing theme color for example)

2024-01-19 09:25 UTC, LunarX requested changes

2024-01-19 09:27 UTC, LunarX requested changes
The navigation bar color issue should also

2024-01-19 09:27 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
> -        }
You should also fix the navigation bar color

2024-01-19 09:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/BaseFragment.kt
> +    abstract val statusBarColor: Int?
How? 🤔

2024-01-19 09:44 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/BaseFragment.kt
> +    abstract val statusBarColor: Int?
Done.

2024-01-23 14:51 UTC, LunarX requested changes
I feel like it'd be easy to miss cases but I don't know what's best

2024-01-23 14:51 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
The statusbar color is not always correct. When the ai prompt is open if you recreate the activity, the statusbar has the the wrong color.

It kinda bothers me that we can forget cases like this, but I don't know how we could possibly find a better way to handle it

2024-01-23 15:08 UTC, LunarX requested changes

2024-01-23 15:08 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Oh, I just realized but it also takes time to set the nav bar from ThreadFragment when navigating to it. (Ui freeze)

2024-01-23 15:09 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Nevermind, I don't know how to build a branch correctly

2024-01-23 15:12 UTC, LunarX requested changes

2024-01-23 15:12 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
The statusbar has the wrong color when you recreate the activity if you did scroll so the toolbar started hovering

2024-01-24 06:31 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Caused by the current MainThread issue of the app, it's another subject.

2024-01-24 08:30 UTC, LunarX requested changes

2024-01-24 08:30 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Also the ThreadFragment has the wrong color if you open the contact bottom sheet and back

2024-01-24 10:09 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Same in ThreadList if you open any bottomSheetDialog then close it.

2024-01-24 12:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Fixed by using `onDestinationChanged()` in the specific case of closing a BottomSheetDialog.

2024-01-25 08:11 UTC, KevinBoulongne commented
> The navigation bar color issue should also

It's ok, the navigation bar color now also.

2024-01-30 07:26 UTC, LunarX requested changes

2024-01-30 07:26 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
When you rotate the screen while the toolbar is elevated the toolbar has the wrong color

2024-02-02 12:29 UTC, LunarX requested changes

2024-02-02 12:53 UTC, LunarX approved these changes

2024-02-02 13:02 UTC, merged