Sort API Routes code
Infomaniak/android-kMail pull request #1669
Opened 2024-01-23 09:20 UTC by KevinBoulongne

Depends on #1656

2024-01-24 09:15 UTC, FabianDevel requested changes

2024-01-24 09:52 UTC, LunarX requested changes

2024-01-24 09:52 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
With this reordering we split features apart in the file. What if we group API calls by feature and have "basic blocks" that are used by multiple features in its own group above everyone else?

2024-01-24 09:55 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Maybe not all of them, just calendar?

2024-01-24 09:55 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
> +    //region Folder
Typo.

2024-01-24 09:58 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
> +        return "${mailbox()}?with=aliases,unseen"
It's supposed to disappear, yes.
But… not in this PR 🤣 
I've put it back.

2024-01-24 10:02 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Problem arises in later PR, fixed there

2024-01-24 10:04 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Fixed in https://github.com/Infomaniak/android-kMail/pull/1665

2024-01-24 14:13 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
>          return "${endpoint}${messages}${offset}${direction}"
It seems you didn't remove the curly braces

2024-01-25 05:21 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
>          return "${endpoint}${messages}${offset}${direction}"
Oh yes sorry, I added them on purpose, for readability.

2024-01-25 07:01 UTC, FabianDevel approved these changes

2024-01-25 07:01 UTC, LunarX approved these changes

2024-01-25 07:02 UTC, merged