Lock MenuDrawer in ThreadFragment
Infomaniak/android-kMail pull request #1672
Opened 2024-01-23 14:04 UTC by KevinBoulongne

Depends on #1671

2024-01-24 12:57 UTC, JorisBodin approved these changes

2024-01-24 15:46 UTC, FabianDevel requested changes

2024-01-24 15:46 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
> +                    (requireActivity() as MainActivity).window.statusBarColor = requireContext().getColor(R.color.backgroundColor)
why this cast ?

2024-01-29 08:01 UTC, FabianDevel approved these changes

2024-02-02 13:17 UTC, merged