Add SuperCollapsedBlock
Infomaniak/android-kMail pull request #1684
Opened 2024-02-01 12:56 UTC by KevinBoulongne

Depends on #1706
Depends on #1683
Depends on https://github.com/Infomaniak/android-core/pull/125

2024-02-08 12:17 UTC, FabianDevel requested changes

2024-02-20 13:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
>              }
Done in another PR: https://github.com/Infomaniak/android-kMail/pull/1707

2024-02-21 16:30 UTC, FabianDevel requested changes

2024-02-21 16:30 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +        return minOf(notNullFirstUnreadIndex, firstDefaultIndex)
```suggestion
        val notNullFirstUnreadIndex = firstUnreadIndex ?: firstDefaultIndex

        return minOf(notNullFirstUnreadIndex, firstDefaultIndex)
```

2024-02-21 16:30 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +                        addMessage(message)
I don't really get this logic, I'll need explanations

2024-02-22 07:41 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +        val shouldCreateSuperCollapsedBlock = shouldSuperCollapsedBlockBeCreated()
The method `shouldSuperCollapsedBlockBeCreated` has a side effect by instantiating an empty mutable map inside a function that should only return a boolean

2024-02-22 07:46 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +        val shouldCreateSuperCollapsedBlock = shouldSuperCollapsedBlockBeCreated()
Nope, it's used in the following inner functions.

2024-02-22 10:43 UTC, FabianDevel approved these changes

2024-02-22 11:51 UTC, tevincent requested changes

2024-02-22 11:51 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesBottomSheetDialog.kt
> +        val margin = context.resources.getDimensionPixelSize(R.dimen.dividerHorizontalPadding).toPx()
`context.resources.getDimensionPixelSize(R.dimen.dividerHorizontalPadding)` already return somthing in pixel. We don't need to convert this value in pixel again.

2024-02-22 11:51 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
> +        val margin = context.resources.getDimensionPixelSize(R.dimen.dividerHorizontalPadding).toPx()
Also here.

2024-02-22 13:06 UTC, merged