Add folder name when we search a mail and when we read a mail
Infomaniak/android-kMail pull request #1699
Opened 2024-02-08 10:20 UTC by tevincent

2024-02-12 15:11 UTC, LunarX requested changes

2024-02-13 16:28 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
> +                )
It's a bit weird to have a `Formatter` showing a dialog. For me, the `View` should handle the viewing, here to show the dialog. What do you think?

2024-02-14 07:45 UTC, tevincent commented on app/src/main/res/drawable/folder_background.xml
> +</shape>
I have removed this background since we're only using `RoundedBackgroundSpan` now.

2024-02-14 07:50 UTC, tevincent commented on app/src/main/res/layout/cardview_thread_item.xml
> +                        tools:visibility="visible" />
Fixed with my modification.

<img width="403" alt="Capture d’écran 2024-02-14 à 08 49 48" src="https://github.com/Infomaniak/android-kMail/assets/149579879/2c67cdda-74f7-427a-adb2-75ae887f91d0">

<img width="439" alt="Capture d’écran 2024-02-14 à 08 49 30" src="https://github.com/Infomaniak/android-kMail/assets/149579879/4768c314-e7af-4663-8e11-74b7b33a831b">


<img width="449" alt="Capture d’écran 2024-02-14 à 08 48 15" src="https://github.com/Infomaniak/android-kMail/assets/149579879/d7e84579-14d0-4f4e-a1ea-386209573b29">

2024-02-15 11:52 UTC, LunarX requested changes
First comments

2024-02-15 14:05 UTC, LunarX requested changes
Some more comments

2024-02-15 14:45 UTC, LunarX requested changes

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        TagColor(R.color.tagBackground, R.color.tagTextColor),
These two resources should be named correctly, they're only used for folder name tags not all tags as their name implies

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        // Colors are not used but here, we just need to compute the tag layouts
```suggestion
        // Colors are not taken into account here. We only call postfixWithTag to compute the layout size
```

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        val maxWidth = if (linesCountDifferent) width else width - positionLastChar
```suggestion
        val maxWidth = if (areLinesCountDifferent) width else width - positionLastChar
```

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +    }
Maybe getEllipsizedTag or something similar? Because I feel like a "configured tag" is not very meaningful

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +    fun getConfiguredTag(): CharSequence {
This should be a String, also make sure no other type is wrong because you often mix up String, CharSequence and Spannable

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +    val modifiedTag = getConfiguredTag()
if you change the name of the function, name this variable accordingly

2024-02-15 14:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +        val endIndex = startIndex + modifiedTag.length - TAG_SEPARATOR.length
Why change the endIndex computation logic here?

2024-02-15 14:45 UTC, LunarX commented on app/src/main/res/font-v26/tag_font.xml
> +  ~ Copyright (C) 2023 Infomaniak Network SA
I don't think this copyright date is correct

2024-02-15 14:45 UTC, LunarX commented on app/src/main/res/layout/cardview_thread_item.xml
> +                    tools:background="@color/tagBackground"
tools:textColor="@color/tagTextColor" ?

2024-02-15 14:45 UTC, LunarX commented on app/src/main/res/layout/cardview_thread_item.xml
> +                    tools:background="@color/grey_background"
Use the correct background and textcolor

2024-02-16 07:11 UTC, KevinBoulongne requested changes

2024-02-16 07:11 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +    private fun CardviewThreadItemBinding.displayFolderName(thread: Thread) {
Fixed in https://github.com/Infomaniak/android-kMail/pull/1699/commits/e73b4752ef740b913e5ceaeca132718b0e3ea1f3

2024-02-16 07:17 UTC, KevinBoulongne requested changes

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        onExternalClicked: (String) -> Unit
```suggestion
        onExternalClicked: (String) -> Unit,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +            getEllipsizeConfiguration(spannedSubjectWithExternal, getFolderName(thread))
```suggestion
            getEllipsizeConfiguration(spannedSubjectWithExternal, getFolderName(thread)),
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        onExternalClicked: (String) -> Unit
```suggestion
        onExternalClicked: (String) -> Unit,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        onExternalClicked: (String) -> Unit
```suggestion
        onExternalClicked: (String) -> Unit,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        TagColor(R.color.externalTagBackground, R.color.externalTagOnBackground)
```suggestion
        TagColor(R.color.externalTagBackground, R.color.externalTagOnBackground),
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        ellipsizeTag: EllipsizeConfiguration
```suggestion
        ellipsizeTag: EllipsizeConfiguration,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        ellipsizeConfiguration: EllipsizeConfiguration
```suggestion
        ellipsizeConfiguration: EllipsizeConfiguration,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        ellipsizeConfiguration
```suggestion
        ellipsizeConfiguration,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +            width
```suggestion
            width,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +            TagColor(RCore.color.black, RCore.color.black)
```suggestion
            TagColor(RCore.color.black, RCore.color.black),
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        val externalMailFlagEnabled: Boolean
```suggestion
        val externalMailFlagEnabled: Boolean,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        val tagTextPaint: TextPaint
```suggestion
        val tagTextPaint: TextPaint,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
> +                    externalMailFlagEnabled = result.mailbox?.externalMailFlagEnabled ?: false
```suggestion
                    externalMailFlagEnabled = result.mailbox?.externalMailFlagEnabled ?: false,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
> +            TagColor(R.color.aiBetaTagBackground, R.color.aiBetaTagTextColor)
```suggestion
            TagColor(R.color.aiBetaTagBackground, R.color.aiBetaTagTextColor),
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
> +                TagColor(R.color.aiBetaTagBackground, R.color.aiBetaTagTextColor)
```suggestion
                TagColor(R.color.aiBetaTagBackground, R.color.aiBetaTagTextColor),
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +    onClicked = onClicked
```suggestion
    onClicked = onClicked,
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +                        .build()
```suggestion
                val tagNameLayout = StaticLayout.Builder.obtain(tag, 0, tag.length, textPaint, maxWidth)
                    .setEllipsizedWidth(maxWidth)
                    .setEllipsize(truncateAt)
                    .setMaxLines(1)
                    .build()
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
> +            cornerRadius = context.resources.getDimension(R.dimen.tagRadius)
```suggestion
            cornerRadius = context.resources.getDimension(R.dimen.tagRadius),
```

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        return EllipsizeConfiguration(maxWidth, TextUtils.TruncateAt.MIDDLE, areLinesCountDifferent, tagsTextPaint)
Import `TextUtils`.

2024-02-16 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
> +        val truncateAt: TextUtils.TruncateAt = TextUtils.TruncateAt.MIDDLE,
Import `TextUtils`.

2024-02-19 12:24 UTC, LunarX approved these changes

2024-02-20 11:23 UTC, LunarX requested changes
Also the computations for the width of tags is wrong. The reason could be that it's too complex to compute everything by hand, maybe simplifying the computation would help

2024-02-21 15:26 UTC, LunarX approved these changes
There's still a bug that sometimes (only when changing dp and sp scales?) the folder names that need to be ellipsized are too big for the screen and therefore don't fit in the screen and are cut off at the edge of the screen

2024-02-21 15:30 UTC, merged