Opening a Thread now correctly marks it as read
Infomaniak/android-kMail pull request #1733
Opened 2024-03-01 11:00 UTC by KevinBoulongne

Depends on #1732

2024-03-01 11:59 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
> +            if (threadState.shouldMarkThreadAsSeen == true) {
Yes, that's on purpose. We only mark a Thread as seen when it's opened.

2024-03-01 12:01 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
> +            if (threadState.shouldMarkThreadAsSeen == true) {
Example of situation where your proposal would be a bad idea :
- Open Thread, read everything, ok.
- Go to Move, Print, or just put the app on background. Or even just scroll the Thread to the top.
- A new mail appears. You don't see it.
- It's marked as seen. You don't know it.
- You go back to ThreadList, you'll never know that you received a new mail.

2024-03-01 13:34 UTC, LunarX requested changes

2024-03-01 13:34 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +        if (threadState.shouldMarkThreadAsSeen == null) threadState.shouldMarkThreadAsSeen = thread.unseenMessagesCount > 0
Can't the boolean be non-nullable and the condition be computed right next to where it's used?

2024-03-01 14:27 UTC, LunarX requested changes
Sometimes my thread is not displayed as "read" when leaving the ThreadFragment but when I open the next thread and come back, the wrongly displayed one is updated and now correctly display as "read"

2024-03-04 08:32 UTC, LunarX approved these changes

2024-03-04 08:32 UTC, merged