UI now correctly updates when marking Thread as seen
Infomaniak/android-kMail pull request #1735
Opened 2024-03-04 08:03 UTC by KevinBoulongne

Depends on #1733

2024-03-04 08:35 UTC, LunarX requested changes

2024-03-04 08:35 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +        formatListJob = globalCoroutineScope.launch {
I think we might need an ensureActive() for it to work

2024-03-07 08:08 UTC, FabianDevel approved these changes

2024-03-07 09:01 UTC, LunarX approved these changes

2024-03-07 09:06 UTC, merged