Add Sentries to try to understand what's happening
Infomaniak/android-kMail pull request #1743
Opened 2024-03-05 12:14 UTC by KevinBoulongne

2024-03-05 13:45 UTC, FabianDevel requested changes

2024-03-05 13:45 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
> +            scope.setExtra("folder.cursor", folder.cursor ?: "null")
```suggestion
            scope.setExtra("folder.cursor", "${folder.cursor}")
```

2024-03-05 13:45 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
> +        addSentryBreadcrumbAboutPaginationInfo(info = paginationInfo)
```suggestion
        addSentryBreadcrumbAboutPaginationInfo(info = paginationInfo)

```

2024-03-06 08:39 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
> +        addSentryBreadcrumbAboutPaginationInfo(info = paginationInfo)
I'll do differently.

2024-03-07 08:06 UTC, FabianDevel requested changes

2024-03-07 08:06 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
> +            if (shouldSkipThisMessage) return@forEach else addedMessagesUids.add(remoteMessage.shortUid)
No else after return

2024-03-07 08:25 UTC, FabianDevel approved these changes

2024-03-07 08:29 UTC, merged