fix: MessageWebviewClient throw an IllegalStateException [RLM_ERR_INVALIDATED_OBJECT]
Infomaniak/android-kMail pull request #1753
Opened 2024-03-12 15:46 UTC by sirambd

Fixes MAIL-ANDROID-3SZ
Fix #1752

2024-03-15 09:32 UTC, KevinBoulongne requested changes

2024-03-15 09:32 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
> -        super.onPageFinished(webView, url)
Why did you remove this `super` call ?

2024-03-18 09:05 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
> -        super.onPageFinished(webView, url)
This super is useless

2024-03-18 11:55 UTC, KevinBoulongne approved these changes

2024-03-18 12:01 UTC, merged