Hide Chevron until Draft loading is finished
Infomaniak/android-kMail pull request #1768
Opened 2024-03-18 08:12 UTC by KevinBoulongne

Depends on #1767

2024-03-19 07:56 UTC, tevincent requested changes

2024-03-19 07:56 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
> +        chevronLoaderVisibilityLayout.isVisible = true
No need to call that layout `visibilitySomething` right?

2024-03-19 09:05 UTC, tevincent approved these changes

2024-03-21 10:07 UTC, FabianDevel requested changes
CI doesn't build because of fDroid

2024-03-25 08:02 UTC, FabianDevel approved these changes

2024-03-26 07:55 UTC, merged