Each Draft field now listens to its own LiveData
Infomaniak/android-kMail pull request #1783
Opened 2024-03-26 07:45 UTC by KevinBoulongne

Depends on #1782

2024-04-02 08:29 UTC, tevincent requested changes

2024-04-02 08:29 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +        if (draft != null) {
`draft?.let`?

2024-04-02 08:29 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +        val isSuccess = draft != null
`emit(draft != null)`?

2024-04-02 12:26 UTC, LunarX requested changes
Also, what happens when the draft remote id changes compared to the one we keep in the UI

2024-04-03 09:00 UTC, tevincent approved these changes

2024-04-04 09:19 UTC, FabianDevel requested changes

2024-04-04 09:31 UTC, FabianDevel requested changes
We shpould save the draftRessource in savedStateHandle, because if the user put the app in background before we put the fetched draft in realm, and the system kill the app, then we won't be able to fetch the draft anymore as the resource will be null

2024-04-15 09:47 UTC, merged