D10: Simplify Draft initialization
Infomaniak/android-kMail pull request #1800
Opened 2024-04-04 08:55 UTC by KevinBoulongne

Depends on #1796

2024-04-16 14:09 UTC, FabianDevel requested changes

2024-04-17 07:29 UTC, FabianDevel approved these changes

2024-04-18 08:18 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +            saveNavArgsToSavedState(it.localUuid)
Maybe we can add the parameter name for `it` ?

2024-04-18 08:21 UTC, tevincent requested changes

2024-04-18 08:21 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +            saveNavArgsToSavedState(it.localUuid)
Maybe we can add the parameter name for it ?

2024-04-18 08:41 UTC, merged