Shortcut `executeDraftActionWhenStopping()` when going to background without changes
Infomaniak/android-kMail pull request #1814
Opened 2024-04-18 07:24 UTC by KevinBoulongne

Depends on #1813

2024-04-18 08:43 UTC, tevincent requested changes

2024-04-18 08:43 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +        }
What do you think about:

```kotlin
private fun isSnapshotTheSame(subjectValue: String?, uiBodyValue: String): Boolean = with(snapshot) {
        return this?.let {
            identityId == fromLiveData.value?.signature?.id?.toString() &&
                    to == toLiveData.valueOrEmpty().toSet() &&
                    cc == ccLiveData.valueOrEmpty().toSet() &&
                    bcc == bccLiveData.valueOrEmpty().toSet() &&
                    subject == subjectValue &&
                    uiBody == uiBodyValue &&
                    attachmentsLocalUuids == attachmentsLiveData.valueOrEmpty().map { it.localUuid }.toSet()
        } ?: false
    }
```

Also, the `@with` is necessary?

2024-04-22 12:19 UTC, FabianDevel requested changes

2024-04-22 12:19 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +                    it.attachmentsLocalUuids == attachmentsLiveData.valueOrEmpty().map { att -> att.localUuid }.toSet()
Put full 'attachment'

2024-04-22 12:19 UTC, tevincent approved these changes

2024-04-22 14:13 UTC, FabianDevel approved these changes

2024-04-22 14:13 UTC, merged