Also save Draft when going on background or FilePicker or IA
Infomaniak/android-kMail pull request #1815
Opened 2024-04-18 07:27 UTC by KevinBoulongne

Depends on #1814

2024-04-18 09:22 UTC, tevincent requested changes

2024-04-18 09:22 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +        attachmentsLiveData.valueOrEmpty().forEach { uiAttachment ->
Maybe we can replace that with a map to assign directly `updatedAttachments`?

2024-04-23 05:08 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
> +            return@map if (localAttachment?.uuid != null) localAttachment.copyFromRealm() else uiAttachment
The comment is misleading, I'gonna update it.

2024-04-23 07:54 UTC, FabianDevel approved these changes

2024-04-23 08:26 UTC, tevincent approved these changes

2024-04-23 08:26 UTC, merged