Add Matomo and Sentry features optout
Infomaniak/android-kMail pull request #1819
Opened 2024-04-18 10:46 UTC by NicolasBourdin88

2024-04-18 12:40 UTC, KevinBoulongne requested changes

2024-04-18 12:40 UTC, KevinBoulongne commented on app/src/main/res/layout/fragment_management_data_settings.xml
> +</com.infomaniak.mail.ui.main.menu.SimpleSettingView>
There's probably a missing setting in your Android Studio that needs to be enabled to add empty lines at end of files.

2024-04-18 12:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/MainApplication.kt
> +    val matomoTracker: Tracker by lazy { buildTracker(!localSettings.isMatomoTrackingEnabled) }
Add named parameter.

2024-04-18 12:40 UTC, KevinBoulongne commented on app/src/main/res/drawable-night/ic_matomo.xml
> +<!--
```suggestion
<?xml version="1.0" encoding="utf-8"?><!--
```

2024-04-18 12:40 UTC, KevinBoulongne commented on app/src/main/res/drawable-night/ic_sentry_text.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Missing header, check everywhere.

2024-04-18 13:03 UTC, LunarX requested changes

2024-04-19 07:53 UTC, sirambd approved these changes

2024-04-19 09:23 UTC, KevinBoulongne requested changes

2024-04-19 09:23 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/MainApplication.kt
> +                if (localSettings.isSentryTrackingEnabled && isRelease) event else null
```suggestion
                if (!BuildConfig.DEBUG && localSettings.isSentryTrackingEnabled) event else null
```

2024-04-19 09:40 UTC, LunarX approved these changes

2024-04-22 07:45 UTC, KevinBoulongne approved these changes

2024-04-22 07:47 UTC, merged

2024-04-22 07:47 UTC, FabianDevel requested changes

2024-04-22 07:47 UTC, FabianDevel commented on app/src/main/res/navigation/main_navigation.xml
> +            android:id="@+id/action_settings_to_managementDataSetting"
```suggestion
            android:id="@+id/action_settings_to_dataManagementSettings"
```

2024-04-22 07:47 UTC, FabianDevel commented on app/src/main/res/navigation/main_navigation.xml
> +            android:id="@+id/action_dataManagement_to_sentrySetting"
```suggestion
            android:id="@+id/action_dataManagementSettingsFragment_to_dataManagementSentrySettingFragment"
```