Detail attachement bug to sentry
Infomaniak/android-kMail pull request #1835
Opened 2024-04-30 11:17 UTC by NicolasBourdin88

- Create new exception to detail bug 
- Hide file name in exception message

2024-04-30 12:03 UTC, FabianDevel requested changes

2024-05-03 04:37 UTC, KevinBoulongne requested changes

2024-05-03 04:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +//endregion
Revert this diff.

2024-05-03 04:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +//endregion
Revert this diff.

2024-05-03 04:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +                        ?: it
There's 2 different `it` here, rename at least one of them _(or maybe all of them)_.

2024-05-03 07:50 UTC, KevinBoulongne requested changes

2024-05-03 07:50 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +                }
Use the IF / ELSE to get the `@IdRes`, then `postValue()` only once.

2024-05-03 07:50 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +                    ?.let { message -> AttachmentMissingFileException(message.replace(file.path, "HIDDEN FILE NAME")) }
Duplicated & hardcoded string.
Move it to const.

2024-05-03 07:50 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +                if (exception.message?.contains("ENAMETOOLONG") == true) {
Hardcoded string, move it to const.

2024-05-03 11:13 UTC, KevinBoulongne requested changes

2024-05-03 11:13 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +                snackbarManager.postValue(context.getString(snackbarMessageId))
```suggestion
                val errorId = if (exception.message?.contains(NAME_TOO_LONG_EXCEPTION) == true) {
                    R.string.errorFileNameTooLong
                } else {
                    RCore.string.errorFileNotFound
                }
                snackbarManager.postValue(context.getString(errorId))
```

2024-05-03 12:09 UTC, FabianDevel requested changes

2024-05-03 12:09 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +            return@use getFileToUpload(context, uri, snackbarManager, attachmentsUploadDir, hashedFileName, inputStream)
```suggestion

            return@use getFileToUpload(context, uri, snackbarManager, attachmentsUploadDir, hashedFileName, inputStream)
```

2024-05-06 11:07 UTC, FabianDevel approved these changes

2024-05-06 11:07 UTC, merged