fix disappearing multi select on a single thread when selecting the "more" action
Infomaniak/android-kMail pull request #1854
Opened 2024-05-15 08:11 UTC by NicolasBourdin88

we should not close multi selection before an action is performed

2024-05-15 08:30 UTC, LunarX requested changes

2024-05-15 08:30 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
> +                            shouldCloseMultiSelection = true
Maybe we could add a comma at the end of that line

2024-05-15 08:34 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
> +                            shouldCloseMultiSelection = true
```suggestion
                            shouldCloseMultiSelection = true,
```

2024-05-15 08:37 UTC, LunarX approved these changes

2024-05-15 08:51 UTC, KevinBoulongne requested changes
I'd like to review this one before being merged.

2024-05-17 06:00 UTC, KevinBoulongne approved these changes

2024-05-17 06:06 UTC, merged