Record access token usage and send sentry if issue arises
Infomaniak/android-kMail pull request #1868
Opened 2024-05-27 07:02 UTC by LunarX

Uses the new AccessTokenUsageInterceptor to record issue with access token to Sentry

Depends on https://github.com/Infomaniak/android-core/pull/185

2024-05-28 12:54 UTC, KevinBoulongne requested changes

2024-05-28 12:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
> +    var accessTokenApiCallRecord by sharedValue<ApiCallRecord>("accessTokenApiCallRecord", null)
```suggestion
    var accessTokenApiCallRecord by sharedValue<ApiCallRecord>("accessTokenApiCallRecordKey", null)
```

2024-05-28 12:54 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/MainApplication.kt
> +            )
```suggestion
            ),
```

2024-05-29 06:10 UTC, tevincent requested changes
Same as Kevin

2024-05-29 12:58 UTC, tevincent approved these changes

2024-05-30 05:33 UTC, KevinBoulongne approved these changes

2024-05-30 06:43 UTC, merged