Return a copy of the list instead of the reference to avoid crash if this list is modified by another threads.
Infomaniak/android-kMail pull request #1882
Opened 2024-05-30 12:55 UTC by tevincent

2024-05-30 13:56 UTC, sirambd approved these changes

2024-05-31 04:27 UTC, KevinBoulongne requested changes

2024-05-31 04:27 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
> +                notificationManagerCompat.notify(notifications.toList())
The crash was that `notificationsByMailboxId[mailboxId]` throws OOB.
How can this fix solve the OOB ? 🤔

2024-05-31 06:47 UTC, KevinBoulongne approved these changes

2024-05-31 06:48 UTC, merged