InformationBlockView is now more configurable
Infomaniak/android-kMail pull request #1893
Opened 2024-06-05 05:57 UTC by TommyDL-Infomaniak

It now has three optional elements: a title, a description, and a button.

<img width="410" alt="Capture d’écran 2024-06-05 à 07 54 51" src="https://github.com/Infomaniak/android-kMail/assets/170427967/7329f0c0-54f6-4495-bca5-66bbc2b66c5f">

2024-06-06 14:11 UTC, LunarX requested changes

2024-06-06 14:11 UTC, LunarX commented on app/src/main/res/layout/view_information_block.xml
> +                    style="@style/Body.Secondary"
The description should only use Body and not Body.Secondary

2024-06-06 14:11 UTC, LunarX commented on app/src/main/res/layout/fragment_ai_proposition.xml
> +                tools:title="@string/aiErrorTooManyRequests"
The already existing InformationBlockView should use the description to stay coherent with the previous style

2024-06-06 14:11 UTC, LunarX commented on app/src/main/res/layout/fragment_no_valid_mailboxes.xml
Your file is not properly formatted

2024-06-06 14:11 UTC, LunarX commented on app/src/main/res/layout/layout_ai_engine_choice.xml
> +        app:title="@string/aiEngineWarning" />
The already existing InformationBlockView should use the description to stay coherent with the previous style

2024-06-06 14:11 UTC, LunarX commented on app/src/main/res/values/attrs.xml
> +        <attr name="showButton" format="boolean" />
Remove the unnecessary `show...` attributes

2024-06-06 14:11 UTC, LunarX commented on app/src/main/res/values/strings.xml
There too many translations, only import the ones you're actually adding/modifying with your PR

2024-06-06 14:14 UTC, LunarX requested changes
Also the title of the PR could be a bit more precise. Your point was not to make the InformationBlockView more configurable but to update the locked mailboxes screen. This, in turn, required the InformationBlockView to be more configurable, but that's not really the main objective of the PR

2024-06-06 14:29 UTC, TommyDL-Infomaniak commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="false"
I moved the WebView on Core, and Sonarcloud was complaining about this option in the corresponding manifest.
This property is used to authorise or not the use of non HTTPS connections. 
By default, this is set to true on old Android versions, for security reasons, I've changed it to false.

2024-06-07 05:02 UTC, KevinBoulongne requested changes

2024-06-07 11:17 UTC, LunarX commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="false"
We enabled this value to be able to load like images inside emails that are still using http

2024-06-07 11:40 UTC, TommyDL-Infomaniak commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="false"
I've changed it back

2024-06-07 11:48 UTC, LunarX requested changes

2024-06-07 11:48 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/views/InformationBlockView.kt
> +            }
You need to support passing the missing defined attributes like title and description

2024-06-07 11:48 UTC, LunarX commented on app/src/main/res/layout/layout_ai_engine_choice.xml
> +        tools:description="@string/aiEngineWarning" />
Use directly the app:description attribute

2024-06-07 11:48 UTC, LunarX commented on app/src/main/res/values-es/strings.xml
> +    <string name="lockedMailboxScreenTitle">Algunos de sus buzones están bloqueados</string>
Not sure `buzones` is the correct word

2024-06-07 11:48 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/newMessage/AiEngineChoiceFragment.kt
> +        choiceBinding.informationBlock.setDescription(R.string.aiEngineWarning)
This value never changes, set it directly from the XML

2024-06-11 07:16 UTC, LunarX requested changes

2024-06-11 07:16 UTC, LunarX commented on app/src/main/res/layout/fragment_no_valid_mailboxes.xml
> +                android:layout_marginHorizontal="@dimen/marginStandard"
Why did you misalign both titles?

2024-06-11 07:16 UTC, LunarX commented on app/src/main/res/layout/view_information_block.xml
At line 36, there's a useless leftover `android:layout_gravity="center_vertical"`

2024-06-11 07:16 UTC, LunarX commented on app/src/main/res/layout/view_information_block.xml
No need to nest a horizontal linear layout inside another horizontal linear layout. It can be expressed as a single linear layout

2024-06-11 07:16 UTC, LunarX commented on app/src/main/res/values/attrs.xml
> +        <attr name="button" format="string" />
You could rename the property as `buttonLabel` here as well while we're at it, to help a bit with coherence

2024-06-11 07:41 UTC, LunarX approved these changes

2024-06-12 08:10 UTC, merged