Fix calendar event canceled detection
Infomaniak/android-kMail pull request #1896
Opened 2024-06-06 06:54 UTC by LunarX

2024-06-06 13:24 UTC, valentinperignon reviewed
Perfect

2024-06-06 13:24 UTC, valentinperignon commented on app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEventResponse.kt
> +    val isCanceled get() = calendarEvent?.status == CalendarEventStatus.CANCELLED
👍 We must check the status of an event, and only the status, to know if it has been canceled of not

2024-06-07 04:53 UTC, KevinBoulongne requested changes

2024-06-07 04:53 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEvent.kt
>          result = 31 * result + attendees.hashCode()
```suggestion
        result = 31 * result + attendees.hashCode()
        result = 31 * result + _status.hashCode()
```

2024-06-07 10:55 UTC, KevinBoulongne approved these changes

2024-06-10 07:19 UTC, merged