Add Bimi feature
Infomaniak/android-kMail pull request #1913
Opened 2024-06-13 09:03 UTC by NicolasBourdin88

We need to be careful about when they will add format PNG to the route, normally it will not affect our route because they (IOS) will just have to add "?format=png" at the end of the call.

2024-06-17 05:42 UTC, KevinBoulongne requested changes

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/Bimi.kt
> +    var isCertified: Boolean = false
```suggestion

    //region Remote data
    @SerialName("svg_content")
    var svgContentUrl: String? = null
    @SerialName("is_certified")
    var isCertified: Boolean = false
    //endregion
```

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
> +        isCorrespondentCertified: Boolean = false
```suggestion
        isCorrespondentCertified: Boolean = false,
```

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +        if (bimi != null && bimi.isCertified) {
```suggestion
        if (bimi?.isCertified == true) {
```

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
> +                threadAdapterCallbacks?.onAttachmentOptionsClicked
Revert this change.

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
> +    private val onContactClicked: ((contact: Recipient, bimi: Bimi?) -> Unit)?
Revert this comma removal.

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
> +    private var bimi: Bimi? = null
Revert this jump line removal.

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
> +                        ).toBundle(),
You can one-line it back if you remove `recipient` parameter name.

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
> +    private var isBimiShow: Boolean = false
Shouldn't it be named `isBimiShown` ?

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
> +    fun loadBimiAvatar(urlBimi: String, correspondent: Correspondent?) = with(binding.avatarImage) {
Rename `urlBimi` into `bimiUrl`.

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
> +                R.array.AvatarColors
```suggestion
                R.array.AvatarColors,
```

2024-06-17 05:42 UTC, KevinBoulongne commented on app/src/main/res/drawable/ic_certified.xml
> +  ~ Copyright (C) 2023-2024 Infomaniak Network SA
```suggestion
  ~ Copyright (C) 2024 Infomaniak Network SA
```

2024-06-17 07:15 UTC, KevinBoulongne requested changes

2024-06-17 07:15 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
> +        onAttachmentOptionsClicked: ((attachment: Attachment) -> Unit)?
```suggestion
        onAttachmentOptionsClicked: ((attachment: Attachment) -> Unit)?,
```

2024-06-18 06:33 UTC, tevincent requested changes

2024-06-18 06:33 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +import com.infomaniak.mail.data.models.*
We avoid wildcards import.

2024-06-18 06:33 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
> +            loadBimiAvatar(ApiRoutes.bimi(bimi.svgContentUrl.orEmpty()), correspondent)
If `bimi.svgContentUrl` is empty, we should call `loadAvatar(correspondent)`right ?

2024-06-18 08:01 UTC, tevincent approved these changes

2024-06-18 08:01 UTC, tevincent commented
@KevinBoulongne can you check again if everything is good for you?

2024-06-25 10:51 UTC, KevinBoulongne requested changes

2024-06-25 10:51 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
> +        this.bimi = newBimi
```suggestion
        bimi = newBimi
```

2024-06-25 10:51 UTC, KevinBoulongne approved these changes

2024-06-25 11:06 UTC, merged