Check before trying to refresh messages for a specific mailbox if this one has already been open once
Infomaniak/android-kMail pull request #1955
Opened 2024-07-10 11:32 UTC by tevincent

This is to avoid logging to Sentry when we try to refresh an unopened mailbox.

2024-07-10 12:33 UTC, sirambd requested changes

2024-07-12 12:55 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
> +        val folder = mailboxFolder ?: FolderController.getFolder(FolderRole.INBOX, realm) ?: run {
What is that ?

2024-07-15 06:37 UTC, TommyDL-Infomaniak requested changes

2024-07-15 06:37 UTC, TommyDL-Infomaniak commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
> +    //We can arrive here for mailboxes we did not opened yet. That's why we check before doing anything.
```suggestion
    // We can arrive here for mailboxes we did not opened yet. That's why we check before doing anything.
```

2024-07-15 06:55 UTC, KevinBoulongne requested changes

2024-07-15 07:02 UTC, KevinBoulongne requested changes

2024-07-15 07:02 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
> +        mailboxFolder: Folder? = null,
Never set, remove it.

2024-07-15 07:03 UTC, KevinBoulongne requested changes

2024-07-15 07:03 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
>              // But if a user never opened this Mailbox, we shouldn't have register it to receive Notifications. So this shouldn't happen.
```suggestion
```

2024-07-15 07:03 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
>              // But if a user never opened this Mailbox, we shouldn't have register it to receive Notifications. So this shouldn't happen.
```suggestion
```

2024-07-15 07:04 UTC, KevinBoulongne requested changes

2024-07-15 07:04 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
> +                Result.success()
Missing return@runCatching here.

2024-07-15 07:19 UTC, KevinBoulongne approved these changes

2024-07-15 07:35 UTC, merged