Changing the way we log the version of WebViews and also handling only official WebViews from Google
Infomaniak/android-kMail pull request #1976
Opened 2024-07-23 08:33 UTC by tevincent

Sadly, I couldn't find a way to redirect to the Huawei AppGallery in case the Huawei WebView is outdated. So we are only checking the WebView version of Google WebViews.

2024-07-24 05:36 UTC, KevinBoulongne requested changes

2024-07-24 05:36 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        // TODO Remove this log in a few weeks/month if we don't have any Sentry anymore
```suggestion
        // TODO: (23/07) Remove this log in a few weeks/month if we don't have any Sentry anymore
```

2024-07-24 11:39 UTC, FabianDevel requested changes

2024-07-24 11:39 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        }
I think we usually put the inner functions on top of the impacted scope. I don't find it really readable like this.

2024-07-24 11:39 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        }
I'd rewrite the entire function like this : 
```suggestion
        fun checkWebViewVersion(canShowWebViewOutdated: Boolean) {
        val webViewPackage = WebViewCompat.getCurrentWebViewPackage(appContext)
        val webViewPackageName = webViewPackage?.packageName

        val (webViewVersionName, webViewMajorVersion) = webViewPackage?.versionName?.let { versionName ->
            val majorVersion = runCatching { versionName.substringBefore('.').toInt() }.getOrDefault(defaultValue = 0)
            versionName to majorVersion
        } ?: (null to 0)

        fun hasOutdatedMajorVersion(): Boolean = when (webViewPackageName) {
                WEBVIEW_OFFICIAL_PACKAGE_NAME -> webViewMajorVersion < WEBVIEW_OFFICIAL_MIN_VERSION
                else -> false // We'll add other package names in the future if needed here
        }

        // TODO: (23/07) Remove this log in a few weeks/month if we don't have any Sentry anymore
        val hasOudatedMajorVersion = hasOutdatedMajorVersion()
        if (hasOudatedMajorVersion) SentryDebug.sendWebViewVersionName(webViewPackageName, webViewVersionName, webViewMajorVersion)
        isWebViewOutdated.value = canShowWebViewOutdated && hasOudatedMajorVersion
    }
```

2024-07-24 11:39 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        }
I kept the inner function here, but I'm not sure about its utility, I think we could just `val hasOutdatedVersion = when {...`

2024-07-24 11:39 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
>              } ?: (null to 0)
Magic values

2024-07-24 12:03 UTC, KevinBoulongne requested changes

2024-07-24 12:03 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        } ?: (null to 0)
Double `0` magic value.

(c) le FAB.

2024-07-24 13:11 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        } ?: (null to 0)
Too late

2024-07-25 05:36 UTC, KevinBoulongne requested changes

2024-07-25 05:36 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +            val majorVersion = runCatching { versionName.substringBefore('.').toInt() }.getOrDefault(defaultValue = 0)
MAGIC NUMBER

2024-07-25 05:36 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +        } ?: (null to 0)
Nope.

2024-07-25 06:06 UTC, KevinBoulongne requested changes

2024-07-25 06:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
> +            webViewMajorVersion
```suggestion
            webViewMajorVersion,
```

2024-07-25 06:07 UTC, FabianDevel approved these changes

2024-07-25 06:08 UTC, KevinBoulongne approved these changes

2024-07-25 06:12 UTC, merged