Add SentryLog when mailboxId uses the default value for configuration
Infomaniak/android-kMail pull request #1986
Opened 2024-07-29 11:05 UTC by TommyDL-Infomaniak

2024-07-29 11:43 UTC, FabianDevel requested changes

2024-07-29 11:43 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +            if (mailboxId == DEFAULT_ID) SentryLog.e(TAG, "RealmConfiguration problem with mailbox content, default ID is used.")
This SentryLog won't show by itself in Sentry.
You should replace it by a `Sentry.captureMessage`

2024-07-29 12:38 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +            if (mailboxId == DEFAULT_ID) Sentry.captureMessage(
```suggestion

            if (mailboxId == DEFAULT_ID) Sentry.captureMessage(
```

2024-07-29 12:39 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +            )
Add curly braces to this `if`.

2024-07-30 05:06 UTC, KevinBoulongne requested changes

2024-07-30 05:08 UTC, KevinBoulongne requested changes

2024-07-30 05:08 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
>      fun deleteMailboxContent(mailboxId: Int, userId: Int = AccountUtils.currentUserId) {
Invert here too.

2024-07-30 05:08 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +                SentryLevel.ERROR
Code is outdated, doesn't make sense anymore.

2024-08-06 11:21 UTC, KevinBoulongne approved these changes

2024-08-06 11:50 UTC, FabianDevel approved these changes

2024-08-06 12:02 UTC, merged