Bump Core & Libs
Infomaniak/android-kMail pull request #2007
Opened 2024-08-12 11:23 UTC by KevinBoulongne

Depends on https://github.com/Infomaniak/android-core/pull/214
Depends on #1972

2024-08-12 12:31 UTC, FabianDevel approved these changes

2024-08-12 12:32 UTC, FabianDevel requested changes
Doesn't build on fDroid

2024-08-13 09:10 UTC, LunarX approved these changes

2024-08-13 09:12 UTC, tevincent approved these changes

2024-08-13 09:14 UTC, FabianDevel approved these changes

2024-08-13 09:14 UTC, merged