Save thread on kDrive
Infomaniak/android-kMail pull request #2088
Opened 2024-11-01 09:41 UTC by NicolasBourdin88

Allow to save Thread in kDrive

<img src="https://github.com/user-attachments/assets/ebeca9e7-edd7-415d-a04d-75533d64b381" alt="Screenshot_1730453896" width="300"/>

In draft because waiting for response for the comportment to adopt while downloading long thread.

2024-11-22 15:12 UTC, FabianDevel requested changes

2024-11-22 16:41 UTC, FabianDevel requested changes

2024-11-22 16:41 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadMessagesViewModel.kt
> +        while (listFileName.contains(fileName)) fileName = "$originalFileName (${postfix++})"
We could probably optimized this function

2024-11-22 16:41 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadProgressDialog.kt
> +        val context = requireContext()
Remove this

2025-02-21 10:11 UTC, tevincent requested changes
I think you have to use `title` instead of `text`. It might have changed since you opened this PR.

<img width="438" alt="Capture d’écran 2025-02-21 à 11 04 12" src="https://github.com/user-attachments/assets/c1008ce5-57c0-4f92-80c5-62bcb0e93b5d" />

2025-02-21 11:42 UTC, tevincent requested changes

2025-02-21 11:42 UTC, tevincent commented on app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
> +    private const val EML_CACHE_DIR = "eml_export"
You can group that with other `DIR`.

2025-02-21 11:42 UTC, tevincent commented on app/src/main/res/values-fr/strings.xml
> +        <item quantity="one">Téléchargement de %d e-mails</item>
`d'un e-mail` ?

2025-02-21 11:47 UTC, tevincent reviewed
And it seems it never delete `eml files` in the `eml_export`.

2025-02-21 15:04 UTC, tevincent approved these changes

2025-02-27 12:07 UTC, FabianDevel approved these changes

2025-02-27 12:21 UTC, merged