Forward email
Infomaniak/android-kMail pull request #675
Opened 2023-03-03 13:10 UTC by KevinBoulongne

Depends on #680

2023-03-06 14:35 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +            quoteWebView.isVisible = true
Maybe use an apply

2023-03-06 14:37 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
> +        } ?: (bodyWithQuote to null)
Could you factorize ?

2023-03-06 14:43 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
> +                }
use clickOnQuickActionBar instead of forward

2023-03-06 14:44 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +    }
Remove this and use clickOnQuickActionBar instead

2023-03-06 15:24 UTC, FabianDevel approved these changes

2023-03-06 17:20 UTC, JorisBodin requested changes

2023-03-06 17:20 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
> +    private fun forwardQuote(message: Message, context: Context): String {
Extention de context stp
Context in extension plz

2023-03-06 17:20 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
Not "to" and "cc" for a forward

2023-03-07 16:18 UTC, JorisBodin approved these changes

2023-03-07 16:19 UTC, merged