Dismiss `loadingTimer` when `refreshThreads()` coroutine is cancelled
Infomaniak/android-kMail pull request #712
Opened 2023-03-13 14:46 UTC by KevinBoulongne

2023-03-13 15:02 UTC, LunarX approved these changes

2023-03-15 09:30 UTC, sirambd requested changes

2023-03-15 09:30 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +        isDownloadingChanges.postValue(false)
It'll be called before `fetchCurrentFolderMessages`

2023-03-15 10:41 UTC, sirambd approved these changes

2023-03-15 10:41 UTC, merged