Add EmptyStates logic
Infomaniak/android-kMail pull request #722
Opened 2023-03-14 13:27 UTC by KevinBoulongne

2023-03-14 16:26 UTC, JorisBodin requested changes

2023-03-15 06:58 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
> +                setEmptyState(R.drawable.ic_empty_folder, "Empty folder", "Empty folder description")
Whoops, this PR was supposed to be in draft, sorry !

2023-03-15 10:10 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
> +                setEmptyState(R.drawable.ic_empty_folder, "Empty folder", "Empty folder description")
Fixed.

2023-03-15 10:51 UTC, JorisBodin approved these changes

2023-03-15 11:40 UTC, sirambd approved these changes

2023-03-15 11:40 UTC, merged