Add AppLock feature
Infomaniak/android-kMail pull request #742
Opened 2023-03-16 15:07 UTC by FabianDevel

Depends on https://github.com/Infomaniak/android-core/pull/45/files

2023-03-21 07:15 UTC, KevinBoulongne requested changes

2023-03-21 07:15 UTC, KevinBoulongne commented on app/build.gradle
This feature doesn't work on our Xiaomi test phone.

2023-03-21 07:38 UTC, FabianDevel commented on app/build.gradle
It isn't link to the android version, it works well on a Honor with same AI, it will need further investigations on specific behaviour of xiaomi

2023-03-23 13:01 UTC, sirambd approved these changes

2023-03-23 13:01 UTC, merged