Add duration to animated Splash icon on Android 12, so it's displayed again
Infomaniak/android-kMail pull request #769
Opened 2023-03-23 14:33 UTC by KevinBoulongne

2023-03-23 15:47 UTC, sirambd requested changes

2023-03-23 15:47 UTC, sirambd commented on app/src/main/res/values-v31/themes.xml
> +        <item name="android:windowSplashScreenAnimationDuration">4242</item>
According to the documentation it is limited to 1000Ms.
> The maximum animation duration should be limited below 1000ms.

2023-03-27 06:26 UTC, LunarX approved these changes

2023-03-27 06:58 UTC, FabianDevel approved these changes

2023-03-27 07:44 UTC, sirambd approved these changes

2023-03-27 07:44 UTC, merged