Fix orphan Messages when Threads algo was cut in the middle
Infomaniak/android-kMail pull request #784
Opened 2023-03-28 12:46 UTC by KevinBoulongne

2023-03-28 15:21 UTC, JorisBodin approved these changes

2023-03-28 15:23 UTC, sirambd requested changes

2023-03-28 15:23 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
> +    fun sendOrphanThreads(previousCursor: String?, folder: Folder, realm: MutableRealm) {
Use TypedRealm instead of MutableRealm

2023-03-29 07:25 UTC, sirambd approved these changes

2023-03-29 07:25 UTC, merged