Stop notif permission requesting
Infomaniak/android-kMail pull request #828
Opened 2023-04-04 14:20 UTC by FabianDevel

Stop requesting notif permissions if the user has manually disabled it by any means.

Fix bug where permissions are not requested for Api < 33

2023-04-06 06:58 UTC, KevinBoulongne approved these changes

2023-04-11 08:52 UTC, JorisBodin requested changes
Merge mainPermissions and getTiramisuPermissions

2023-04-12 12:09 UTC, KevinBoulongne approved these changes

2023-04-12 14:24 UTC, sirambd approved these changes

2023-04-12 14:27 UTC, JorisBodin approved these changes

2023-04-12 14:27 UTC, merged