Highlights matched text when adding contacts to an email
Infomaniak/android-kMail pull request #830
Opened 2023-04-04 14:29 UTC by LunarX

Depends on #829

2023-04-05 09:39 UTC, KevinBoulongne requested changes

2023-04-05 09:39 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
> +        if (nameStartIndex > -1) userName.highlight(nameStartIndex, nameStartIndex + length)
Magic value.

Did you mean `NOT_SET` ?

2023-04-05 09:39 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
> +        if (emailStartIndex > -1 && userEmail.text.isNotBlank()) userEmail.highlight(emailStartIndex, emailStartIndex + length)
Magic value.

Did you mean `NOT_SET` ?

2023-04-05 09:39 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
> +        if (emailStartIndex > -1 && userEmail.text.isNotBlank()) userEmail.highlight(emailStartIndex, emailStartIndex + length)
The `userEmail` can be blank, but not the `userName` ? Isn't it the opposite ?

2023-04-05 09:39 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
> +                val matches = nameMatchedIndex > -1 || emailMatchedIndex > -1
Magic value twice.

Did you mean `NOT_SET` ?

2023-04-05 10:09 UTC, KevinBoulongne approved these changes

2023-04-05 13:12 UTC, FabianDevel requested changes

2023-04-06 06:32 UTC, FabianDevel approved these changes

2023-04-06 06:45 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
> +        return if (getItemViewType(position) == KNOWN_CONTACT.id) matchedContacts[position].contact.id!! else 0
```suggestion
        return if (getItemViewType(position) == KNOWN_CONTACT.id) matchedContacts[position].contact.id!! else 0L
```

2023-04-06 06:47 UTC, merged