Add missing actions in Multiselection BottomSheet
Infomaniak/android-kMail pull request #841
Opened 2023-04-06 12:32 UTC by LunarX

2023-04-11 08:55 UTC, JorisBodin approved these changes

2023-04-11 10:01 UTC, KevinBoulongne requested changes

2023-04-11 10:01 UTC, KevinBoulongne commented on app/src/main/res/drawable/ic_non_spam.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Add missing file header.

2023-04-11 10:57 UTC, KevinBoulongne requested changes

2023-04-11 10:57 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
> +        // TODO : When decided by UI/UX change how the icon is displayed when trying to archive from inside the archive folder
```suggestion
        // TODO : When decided by UI/UX, change how the icon is displayed (when trying to archive from inside the Archive folder).
```

2023-04-11 11:49 UTC, FabianDevel requested changes

2023-04-11 11:49 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
> +            var shouldUnFavorite = selectedThreads.isNotEmpty()
```suggestion
            var shouldUnread = true
            var shouldUnfavorite = selectedThreads.isNotEmpty()
```

2023-04-11 11:49 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
> +        return -1
```suggestion
        }

        return -1
```

2023-04-11 12:21 UTC, sirambd requested changes

2023-04-11 12:21 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
> +                    isMultiSelectOn = false
Already done below

2023-04-11 12:21 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
> +                    isMultiSelectOn = false
useless

2023-04-11 12:21 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
> +                    mainViewModel.deleteThreads(selectedThreadsUids)
```suggestion
                   deleteThreads(selectedThreadsUids)
```

2023-04-12 05:52 UTC, KevinBoulongne approved these changes

2023-04-12 08:26 UTC, JorisBodin approved these changes

2023-04-12 08:26 UTC, merged