Don't start `DraftsActionsWorker` when adding Attachment
Infomaniak/android-kMail pull request #853
Opened 2023-04-12 08:38 UTC by KevinBoulongne

2023-04-12 08:48 UTC, FabianDevel approved these changes

2023-04-14 10:06 UTC, sirambd requested changes

2023-04-14 10:06 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +
Added a comment to explain that it is temporary

2023-04-14 11:43 UTC, JorisBodin approved these changes

2023-04-14 11:43 UTC, merged