fix: Download manager for api below 29 need write permission
Infomaniak/android-kMail pull request #857
Opened 2023-04-12 14:11 UTC by sirambd

- [fix: Download manager for api below 29 need write permission](https://github.com/Infomaniak/android-kMail/commit/42a9a681ade9222522ff0e4859eb5768c94e2dfd)

**Stacktrace**
```
java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/kMail-attachments-2023 0407 Article DauBé supplém.zip: Neither user 10176 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
    at android.os.Parcel.createException(Parcel.java:1966)
    at android.os.Parcel.readException(Parcel.java:1934)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
    at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
    at android.content.ContentResolver.insert(ContentResolver.java:1594)
    at android.app.DownloadManager.enqueue(DownloadManager.java:1479)
    at com.infomaniak.lib.core.utils.DownloadManagerUtils.scheduleDownload(DownloadManagerUtils.kt:49)
    at com.infomaniak.mail.ui.main.thread.ThreadFragment.downloadAllAttachments(ThreadFragment.kt:327)
    at com.infomaniak.mail.ui.main.thread.ThreadFragment.access$downloadAllAttachments(ThreadFragment.kt:74)
    at com.infomaniak.mail.ui.main.thread.ThreadFragment$setupAdapter$1$2$5.invoke(ThreadFragment.kt:254)
    at com.infomaniak.mail.ui.main.thread.ThreadFragment$setupAdapter$1$2$5.invoke(ThreadFragment.kt:252)
    at com.infomaniak.mail.ui.main.thread.ThreadAdapter.bindAttachment$lambda$20$lambda$19(ThreadAdapter.kt:316)
    at com.infomaniak.mail.ui.main.thread.ThreadAdapter.$r8$lambda$YowpGaowEVIUthc43JaDiEINJ4E
    at com.infomaniak.mail.ui.main.thread.ThreadAdapter$$ExternalSyntheticLambda4.onClick
    at android.view.View.performClick(View.java:7339)
    at android.widget.TextView.performClick(TextView.java:14275)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
    at android.view.View.performClickInternal(View.java:7305)
    at android.view.View.access$3200(View.java:846)
    at android.view.View$PerformClick.run(View.java:27787)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7078)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

2023-04-12 14:39 UTC, JorisBodin approved these changes

2023-04-13 05:47 UTC, KevinBoulongne requested changes

2023-04-13 05:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
> +     * Request storage permission only for android Api below 29.
```suggestion
     * Request storage permission only for Android API below 29.
```

2023-04-13 05:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
> +        @get:DeprecatedSinceApi(Build.VERSION_CODES.Q, "Only used for downloadManager below api 29")
```suggestion
        @get:DeprecatedSinceApi(Build.VERSION_CODES.Q, "Only used for DownloadManager below API 29")
```

2023-04-13 05:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
> +     * Register storage permission only for android Api below 29.
```suggestion
     * Register storage permission only for Android API below 29.
```

2023-04-13 05:48 UTC, KevinBoulongne approved these changes

2023-04-13 05:48 UTC, merged