Attach mailbox tunnel
Infomaniak/android-kMail pull request #884
Opened 2023-04-20 06:54 UTC by FabianDevel

- Add a screen to attach an existing mailbox to your account
- Remove AdjustViewBounds from theme because it clashes with material TextInputLayout's end icon
- Move Mailbox model to a new mailbox package

2023-04-20 08:35 UTC, KevinBoulongne requested changes

2023-04-20 08:35 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/mailbox/MailboxLinkedResult.kt
> +class MailboxLinkedResult(
Make it a `data class`.

2023-04-20 11:08 UTC, LunarX requested changes

2023-04-20 11:14 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
> +        passwordInput.text?.isNotBlank() == true && mailInput.text?.trim().toString().isEmail()
The `blank` check if for the password.

2023-04-20 11:22 UTC, FabianDevel commented on app/src/main/res/layout/fragment_attach_mailbox.xml
> +            app:layout_constraintTop_toBottomOf="@id/mailInputLayout">
I don't really know for this. Once I spoke with the designer about material input and we agreed on keeping material "native" design, so here I kept it. 
I'll ask her

2023-04-20 12:24 UTC, FabianDevel commented on app/src/main/res/layout/fragment_attach_mailbox.xml
> +        android:layout_height="match_parent">
Linear Layout prevent us from using max_width and match_parent at the same time, which makes the primaryTextButton too large in landscape mode. We should use constraint layout in these views

2023-04-20 12:28 UTC, FabianDevel commented on app/src/main/res/layout/fragment_attach_mailbox.xml
The formatting still need UX answer, for now it is more important to keep this helper, but this may change in the future

2023-04-24 06:27 UTC, FabianDevel commented on app/src/main/res/layout/fragment_attach_mailbox.xml
It's no problem to apply it to the whole activity

2023-05-03 15:23 UTC, JorisBodin approved these changes

2023-05-04 06:58 UTC, KevinBoulongne approved these changes

2023-05-04 06:59 UTC, merged