Fix blockquotes display, wrap long lines and refactor + optimize code for future mail processing
Infomaniak/android-kMail pull request #890
Opened 2023-04-25 07:32 UTC by LunarX

2023-04-25 08:48 UTC, FabianDevel requested changes
We could create a WebViewUtils class which can be instantiated as lazy by NewMessageFragment and ThreadAdapter
This class could wrap the 3 lazy and the load/process functions to factorize it

2023-04-25 10:06 UTC, KevinBoulongne requested changes

2023-04-25 10:06 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
> +        settings.useWideViewPort = true
```suggestion
        settings.apply {
            useWideViewPort = true
            loadWithOverviewMode = true
        }
```

2023-04-25 13:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
> +        settings.useWideViewPort = true
See in later PR

2023-04-25 13:45 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +        }
See in later PR

2023-04-25 14:48 UTC, FabianDevel requested changes

2023-04-25 14:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +        }
This should also be a part of WebViewUtils

2023-04-25 14:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
> +        return inject()
```suggestion
        registerMetaViewPort()

        return inject()
```

2023-04-26 14:59 UTC, JorisBodin approved these changes

2023-04-26 14:59 UTC, FabianDevel approved these changes

2023-05-01 07:26 UTC, KevinBoulongne approved these changes

2023-05-01 07:27 UTC, merged