Add Attachment sentry
Infomaniak/android-kMail pull request #914
Opened 2023-05-03 08:03 UTC by KevinBoulongne

2023-05-03 15:07 UTC, JorisBodin requested changes
You added `errorCorruptAttachment` but forgot to use it

2023-05-04 09:00 UTC, FabianDevel requested changes

2023-05-04 09:04 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +                applicationContext.showToast(R.string.errorCorruptAttachment)
```suggestion
                }

                applicationContext.showToast(R.string.errorCorruptAttachment)
```

2023-05-04 09:06 UTC, JorisBodin approved these changes

2023-05-04 09:08 UTC, FabianDevel approved these changes

2023-05-04 09:56 UTC, merged